### ISSUE TITLE
UCD  ECOSYSTEM ACCOUNTING 

### ISSUE THREAD

**Issue by krosza** [Augmint/augmint-web#3]
https://docs.google.com/spreadsheets/d/1R5RURTLQv0XBY46XN3RVojHdv9LAQcNJbYZeg1ig_CU/edit?usp=sharing

first draft, to be discussed
a double book keeping model
only some parts requires coding
it is the  core UCD  part only
ETH part should be prepared to
**The purpose to create  the ecosystem's indicators  for  monetary management ** ( market intervention)

**Comment by szerintedmi** [comment]
it's not relevant anymore (already implemented)
