### ISSUE TITLE
deal w/ js injection in tx narrative

### ISSUE THREAD

**Issue by szerintedmi** [Augmint/augmint-web#58]

**Comment by szerintedmi** [comment]
@phraktle ?

**Comment by phraktle** [comment]
steps to reproduce?

**Comment by szerintedmi** [comment]
I just went through on old bugs. I added this when token symbol hack happened on IDEX or whichever exchange. So just checking if we are ok in this regard.

**Comment by phraktle** [comment]
Frontend code properly escapes everything unless one explicitly requests otherwise (eg. with `dangerouslySetInnerHTML`). Closing, unless you have a specific case where you think something fishy is happening.
