### ISSUE TITLE
exchange fiat form cropped on Firefox

### ISSUE THREAD

**Issue by szerintedmi** [Augmint/augmint-web#599]
in #557 branch it's cropped and weirdly placed.
![image](https://user-images.githubusercontent.com/7456451/56866019-c3c19780-69cc-11e9-8a5b-d315633c354e.png)

**Comment by szerintedmi** [comment]
@phraktle : anyone is looking at these issues and picking/assigning them?

**Comment by phraktle** [comment]
Was addressed in https://github.com/Augmint/augmint-web/commit/3bd959d74716b890fb75a47b021f2eb3075e94e2
