### ISSUE TITLE
how to get auer box is not needed on exchange fiat page

### ISSUE THREAD

**Issue by szerintedmi** [Augmint/augmint-web#604]
![Screenshot_20190501-121014_Trust Wallet](https://user-images.githubusercontent.com/7456451/57015065-bf82bd80-6c0a-11e9-8978-a27622a9506d.jpg)

**Comment by phraktle** [comment]
I think this pretty much only makes sense on the "My Account" page, as a side-bar when you have zero A-EUR. What do you think @szerintedmi ?

**Comment by szerintedmi** [comment]
I think it makes sense on lock and send AEUR pages too. 
This notification has so many issues (people don't notice it, the page it leads to is outdated / convoluted etc.). 
I would just do a quick fix for now: remove it from this page (and others where it doesn't make sense). We should fix it holistically when we redo the whole onboarding.

**Comment by phraktle** [comment]
My suggested fix is to only show it on the account page.

**Comment by szerintedmi** [comment]
it makes sense on send and lock , I wouldn't remove from there despite it's ugly. 

![image](https://user-images.githubusercontent.com/7456451/57024784-5eb8ac80-6c2d-11e9-97e2-948708864296.png)

![image](https://user-images.githubusercontent.com/7456451/57024821-74c66d00-6c2d-11e9-9474-5e468f977806.png)
