### ISSUE TITLE
Tx not displayed in notifications until receipt received

### ISSUE THREAD

**Issue by szerintedmi** [Augmint/augmint-web#605]
We already have tx hash but no receipt (or confirmation?) yet. It shows something is pending but the transaction is not in the notifications list. 

![image](https://user-images.githubusercontent.com/7456451/57021867-4fcdfc00-6c25-11e9-9023-94edefb0dcd0.png)

When first confirmation arrives the tx is displayed correctly at notifications

![txrece](https://user-images.githubusercontent.com/7456451/57022495-3a59d180-6c27-11e9-8216-73b49887a5c6.gif)

**Comment by ejulcsi** [comment]
@szerintedmi 
couldn't reproduce, the notifications are shown in both rinkeby and tesrpc networks
