### ISSUE TITLE
can't collect my defaulted loan (regression)

### ISSUE THREAD

**Issue by szerintedmi** [Augmint/augmint-web#609]
We used to have a collect button for defaulted but not yet collected loans. It is important to get back my leftover collateral in case I forgot to repay and the collector job is not running for any reason (e.g. it's not implemented yet  and nobody clicks on the link from stability report page :) )
![image](https://user-images.githubusercontent.com/7456451/57074125-e6a8c000-6cda-11e9-8071-f896aeefa1ff.png)

**Comment by phraktle** [comment]
do you perchance have a link to a prior version where this worked?

**Comment by szerintedmi** [comment]
well, sure, it must be somewhere in the netlify deploy history.
I don't think it's high prio - it can be accessed via the stability report page. I just wanted to have it in the backlog

**Comment by phraktle** [comment]
I was just wondering if this is something that was broken recently or a while ago... :)
