### ISSUE TITLE
Notification of tx revert error is cluttered

### ISSUE THREAD

**Issue by szerintedmi** [Augmint/augmint-web#622]
When tx reverts the error message is cluttered with details which makes no sense for users. Also overflows the notification panel. Hide details by default 
NB: easiest way to produce a tx error is to lower the gas limit in Metamask popup before approving the tx

![txerror](https://user-images.githubusercontent.com/7456451/57411343-301a7300-71e5-11e9-824d-3e6ac41890af.gif)

**Comment by phraktle** [comment]
Should ee even show error details? For regular users it doesn’t help, developers can view on etherscan.
