### ISSUE TITLE
Balance decimals on account page shown without trailing 0

### ISSUE THREAD

**Issue by szerintedmi** [Augmint/augmint-web#623]
should be formatted as everywhere else
![image](https://user-images.githubusercontent.com/7456451/57414538-6f9a8c80-71f0-11e9-9aa2-d2fa21cbd7e4.png)

also wrong in dropdown shown from topnav 
![image](https://user-images.githubusercontent.com/7456451/57416263-63fe9400-71f7-11e9-8d80-c0beee826f26.png)

**Comment by phraktle** [comment]
Using the <AEUR ...> tag would fix this.
