### ISSUE TITLE
 A€ symbol for total loan / lock amount is breaking to new line on my account page

### ISSUE THREAD

**Issue by szerintedmi** [Augmint/augmint-web#624]
![image](https://user-images.githubusercontent.com/7456451/57414593-b092a100-71f0-11e9-91d1-aece0b319331.png)

![image](https://user-images.githubusercontent.com/7456451/57414611-c1431700-71f0-11e9-8c22-9a7d7e063b92.png)

**Comment by phraktle** [comment]
Using the <AEUR ...> tag would fix this.

Loans/locks should break below eachother when they are wider.
